language: python
dist: xenial

matrix:
  include:
    - python: 3.7
      env: TOXENV=lint
    - python: 3.7
      env: TOXENV=cover
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
install:
  - sudo apt-get install redis-server -y
  - pip install tox
script:
  - tox
